### ISSUE TITLE
Not Build corelib

### ISSUE THREAD

**Issue by Mahdihp** [europeana/corelib#170]
Not Build corelib ...
![image](https://user-images.githubusercontent.com/6378625/67233491-29f51780-f450-11e9-993a-00fc185e33e2.png)

**Comment by P-Ehlert** [comment]
Hi Mahdihp, the Europeana Parent Pom project can be found here: https://github.com/europeana/europeana-parent-pom, but it's probably easier to add our repository http://artifactory.eanadev.org/artifactory/libs-release to your Maven settings.
