### ISSUE TITLE
Non-resolvable parent POM for eu.europeana:corelib:2.9.3-SNAPSHOT:

### ISSUE THREAD

**Issue by Mahdihp** [europeana/corelib#171]
/usr/lib/jvm/jdk-12.0.1/bin/java -Dmaven.multiModuleProjectDirectory=/home/mahdi/IdeaProjects/MasterProject/corelib/corelib -Dmaven.home=/home/mahdi/Apps/IntellijIDEA/idea-IU-183.5429.30/plugins/maven/lib/maven3 -Dclassworlds.conf=/home/mahdi/Apps/IntellijIDEA/idea-IU-183.5429.30/plugins/maven/lib/maven3/bin/m2.conf -javaagent:/home/mahdi/Apps/IntellijIDEA/idea-IU-183.5429.30/lib/idea_rt.jar=44963:/home/mahdi/Apps/IntellijIDEA/idea-IU-183.5429.30/bin -Dfile.encoding=UTF-8 -classpath /home/mahdi/Apps/IntellijIDEA/idea-IU-183.5429.30/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2018.3.4 package -P external,internal
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for eu.europeana:corelib:2.9.3-SNAPSHOT: Failure to find eu.europeana:europeana-parent-pom:pom:2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 8, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project eu.europeana:corelib:2.9.3-SNAPSHOT (/home/mahdi/IdeaProjects/MasterProject/corelib/corelib/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for eu.europeana:corelib:2.9.3-SNAPSHOT: Failure to find eu.europeana:europeana-parent-pom:pom:2.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 8, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Process finished with exit code 1

**Comment by P-Ehlert** [comment]
Hi Mahdihp, the Europeana Parent Pom project can be found here: https://github.com/europeana/europeana-parent-pom, but it's probably easier to add our repository http://artifactory.eanadev.org/artifactory/libs-release to your Maven settings.
